### ISSUE TITLE
Pub.dev?

### ISSUE THREAD

**Issue by codeituprightnow** [rutvik110/Flutter-Infinite-Pagination#2]
This library is a great, universal pattern for pagination with riverpod, and it would be great on pub.dev

Can you please also specify a license to the current project? Thank you ☺️

**Comment by rutvik110** [comment]
Hey thanx! 🙏
I actually don't have any plans to put it on pub.dev . The job for this implementation was to give you a basic understanding of how you could handle basic infinite pagination scenarios and using riverpod,freezed and firebase were just one of many things you could've done this with.  
Also there's many behaviours that one would prefer over the other so the best thing you could do is just fork this repo and build upon this basic foundation as you may seem good.

I'm closing this issue now. If there's anything else then feel free to file another issue for it.
